In [1]:
print("hello world!")

hello world!

In [49]:
#list_category = ['Area','Length','Time','ALTSHIPUNIT','Margin','Cost','Cartons']
#list_code = ('50','30','130','80','500','510','1001')
#list_category = ('Acre','Square Foot','Square Centimeter','Square Inch','Square Kilometer','Square Meter','Square Mile','Square Yard','BRR','CAD','US Cent','Dozen','P24Pack','Centimeter','Inch','Kilometer','Meter','Mile','Millimeter','Yard','Foot','Hour','12 Hour','16 Hour','24 Hour','4 Hour','40 Hour','8 Hour','Day','Minute','Month','Week','Year','Cubic Centimeter','Cubic Foot','Cubic Inch','Cubic Meter','Cubic Yard','Fluid Ounce','Pint','Grain','Gram','Kilogram','Metric Pound','Metric Ton','Milligram','Ton','Percent','Default Weight Unit','Default Volume Unit','AltShip Unit','Margin','Cost','Case')
#list_code = ('1','2','3','4','5','6','7','8','9','10','16','17','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','48','51','52','53','54','55','56','58','59','100','700','800','5,000','5,100','10,001')

#list_category = ('Acre','Square Foot','Square Centimeter','Square Inch','Square Kilometer','Square Meter','Square Mile','Square Yard','BRR','CAD','US Cent','Dozen','P24Pack','Centimeter','Inch','Kilometer','Meter','Mile','Millimeter','Yard','Foot','Hour','12 Hour','16 Hour','24 Hour','4 Hour','40 Hour','8 Hour','Day','Minute','Month','Week','Year','Cubic Centimeter','Cubic Inch','Cubic Meter','Cubic Yard','Fluid Ounce','Pint','Grain','Gram','Kilogram','Metric Pound','Metric Ton','Milligram','Ton','Percent','Default Weight Unit','Default Volume Unit','AltShip Unit','Margin','Cost','Case')
#list_code = ('1','2','3','4','5','6','7','8','9','10','16','17','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','42','43','44','45','48','51','52','53','54','55','56','58','59','100','700','800','5,000','5,100','10,001')

list_category = ('Area','Length','Time','Percentage','ALTSHIPUNIT','Margin','Cost','Cartons')
list_code = ('50','30','130','1,003','80','500','510','1,001')


k=0
j=0
print(len(list_category))
for j in range (len(list_category)):
    for k in range (k<=len(list_category)):
        print (list_code[j]+ ' ' + list_category[j])

8
50 Area
30 Length
130 Time
1,003 Percentage
80 ALTSHIPUNIT
500 Margin
510 Cost
1,001 Cartons

In [6]:
list2=('50','110','90','30','130','70','10','1,003','1,002','80','500','510','1,001')
for i in list2:
    print(i)

50
110
90
30
130
70
10
1,003
1,002
80
500
510
1,001

In [44]:
original_copy= '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');'''
print(original_copy+"\n")
comilla = "'"
nombre = 'CARLOS'
numero = '2300'
query = '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'''
query2 = '''', N'''
query3 = ''' maps to '''
query4='''', N'''
query5= ''');'''

list_category = ['Area','Length','Time','ALTSHIPUNIT','Margin','Cost','Cartons']
list_code = ('50','30','130','80','500','510','1001')
k=0
j=0
print(len(list_category))
for j in range (len(list_category)):
    for k in range (k<=len(list_category)):
        print (query+comilla + list_category[j]+query2+comilla+list_category[j]+query3+list_code[j]+query4+comilla+ list_code[j]+comilla+query5)

INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');

7
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Area', N'Area maps to 50', N'50');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Length', N'Length maps to 30', N'30');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Time', N'Time maps to 130', N'130');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'ALTSHIPUNIT', N'ALTSHIPUNIT maps to 80', N'80');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Margin', N'Margin maps to 500', N'500');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cost', N'Cost maps to 510', N'510');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cartons', N'Cartons maps to 1001', N'1001');

In [46]:
original_copy= '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');'''
print(original_copy+"\n")
comilla = "'"
nombre = 'CARLOS'
numero = '2300'
query = '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'''
query2 = '''', N'''
query3 = ''' maps to '''
query4='''', N'''
query5= ''');'''

list_category = ('Acre','Square Foot','Square Centimeter','Square Inch','Square Kilometer','Square Meter','Square Mile','Square Yard','BRR','CAD','US Cent','Dozen','P24Pack','Centimeter','Inch','Kilometer','Meter','Mile','Millimeter','Yard','Foot','Hour','12 Hour','16 Hour','24 Hour','4 Hour','40 Hour','8 Hour','Day','Minute','Month','Week','Year','Cubic Centimeter','Cubic Foot','Cubic Inch','Cubic Meter','Cubic Yard','Fluid Ounce','Pint','Grain','Gram','Kilogram','Metric Pound','Metric Ton','Milligram','Ton','Percent','Default Weight Unit','Default Volume Unit','AltShip Unit','Margin','Cost','Case')
list_code = ('1','2','3','4','5','6','7','8','9','10','16','17','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','48','51','52','53','54','55','56','58','59','100','700','800','5,000','5,100','10,001')

k=0
j=0
print(len(list_category))
for j in range (len(list_category)):
    for k in range (k<=len(list_category)):
        print (query+comilla + list_category[j]+query2+comilla+list_category[j]+query3+list_code[j]+query4+comilla+ list_code[j]+comilla+query5)

INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');

54
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Acre', N'Acre maps to 1', N'1');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Foot', N'Square Foot maps to 2', N'2');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Centimeter', N'Square Centimeter maps to 3', N'3');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Inch', N'Square Inch maps to 4', N'4');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Kilometer', N'Square Kilometer maps to 5', N'5');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Meter', N'Square Meter maps to 6', N'6');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Mile', N'Square Mile maps to 7', N'7');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Yard', N'Square Yard maps to 8', N'8');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'BRR', N'BRR maps to 9', N'9');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CAD', N'CAD maps to 10', N'10');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'US Cent', N'US Cent maps to 16', N'16');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Dozen', N'Dozen maps to 17', N'17');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'P24Pack', N'P24Pack maps to 19', N'19');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Centimeter', N'Centimeter maps to 20', N'20');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Inch', N'Inch maps to 21', N'21');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Kilometer', N'Kilometer maps to 22', N'22');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Meter', N'Meter maps to 23', N'23');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Mile', N'Mile maps to 24', N'24');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Millimeter', N'Millimeter maps to 25', N'25');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Yard', N'Yard maps to 26', N'26');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Foot', N'Foot maps to 27', N'27');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Hour', N'Hour maps to 28', N'28');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'12 Hour', N'12 Hour maps to 29', N'29');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'16 Hour', N'16 Hour maps to 30', N'30');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'24 Hour', N'24 Hour maps to 31', N'31');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'4 Hour', N'4 Hour maps to 32', N'32');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'40 Hour', N'40 Hour maps to 33', N'33');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'8 Hour', N'8 Hour maps to 34', N'34');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Day', N'Day maps to 35', N'35');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Minute', N'Minute maps to 36', N'36');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Month', N'Month maps to 37', N'37');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Week', N'Week maps to 38', N'38');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Year', N'Year maps to 39', N'39');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Centimeter', N'Cubic Centimeter maps to 40', N'40');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Foot', N'Cubic Foot maps to 41', N'41');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Inch', N'Cubic Inch maps to 42', N'42');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Meter', N'Cubic Meter maps to 43', N'43');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Yard', N'Cubic Yard maps to 44', N'44');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Fluid Ounce', N'Fluid Ounce maps to 45', N'45');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Pint', N'Pint maps to 48', N'48');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Grain', N'Grain maps to 51', N'51');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Gram', N'Gram maps to 52', N'52');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Kilogram', N'Kilogram maps to 53', N'53');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Metric Pound', N'Metric Pound maps to 54', N'54');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Metric Ton', N'Metric Ton maps to 55', N'55');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Milligram', N'Milligram maps to 56', N'56');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Ton', N'Ton maps to 58', N'58');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Percent', N'Percent maps to 59', N'59');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Default Weight Unit', N'Default Weight Unit maps to 100', N'100');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Default Volume Unit', N'Default Volume Unit maps to 700', N'700');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'AltShip Unit', N'AltShip Unit maps to 800', N'800');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Margin', N'Margin maps to 5,000', N'5,000');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cost', N'Cost maps to 5,100', N'5,100');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Case', N'Case maps to 10,001', N'10,001');

In [48]:
original_copy= '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');'''
print(original_copy+"\n")
comilla = "'"
nombre = 'CARLOS'
numero = '2300'
query = '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'''
query2 = '''', N'''
query3 = ''' maps to '''
query4='''', N'''
query5= ''');'''

list_category = ('Acre','Square Foot','Square Centimeter','Square Inch','Square Kilometer','Square Meter','Square Mile','Square Yard','BRR','CAD','US Cent','Dozen','P24Pack','Centimeter','Inch','Kilometer','Meter','Mile','Millimeter','Yard','Foot','Hour','12 Hour','16 Hour','24 Hour','4 Hour','40 Hour','8 Hour','Day','Minute','Month','Week','Year','Cubic Centimeter','Cubic Inch','Cubic Meter','Cubic Yard','Fluid Ounce','Pint','Grain','Gram','Kilogram','Metric Pound','Metric Ton','Milligram','Ton','Percent','Default Weight Unit','Default Volume Unit','AltShip Unit','Margin','Cost','Case')
list_code = ('1','2','3','4','5','6','7','8','9','10','16','17','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','42','43','44','45','48','51','52','53','54','55','56','58','59','100','700','800','5,000','5,100','10,001')

k=0
j=0
print(len(list_category))
for j in range (len(list_category)):
    for k in range (k<=len(list_category)):
        print (query+comilla + list_category[j]+query2+comilla+list_category[j]+query3+list_code[j]+query4+comilla+ list_code[j]+comilla+query5)

INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');

53
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Acre', N'Acre maps to 1', N'1');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Foot', N'Square Foot maps to 2', N'2');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Centimeter', N'Square Centimeter maps to 3', N'3');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Inch', N'Square Inch maps to 4', N'4');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Kilometer', N'Square Kilometer maps to 5', N'5');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Meter', N'Square Meter maps to 6', N'6');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Mile', N'Square Mile maps to 7', N'7');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Square Yard', N'Square Yard maps to 8', N'8');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'BRR', N'BRR maps to 9', N'9');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CAD', N'CAD maps to 10', N'10');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'US Cent', N'US Cent maps to 16', N'16');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Dozen', N'Dozen maps to 17', N'17');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'P24Pack', N'P24Pack maps to 19', N'19');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Centimeter', N'Centimeter maps to 20', N'20');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Inch', N'Inch maps to 21', N'21');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Kilometer', N'Kilometer maps to 22', N'22');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Meter', N'Meter maps to 23', N'23');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Mile', N'Mile maps to 24', N'24');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Millimeter', N'Millimeter maps to 25', N'25');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Yard', N'Yard maps to 26', N'26');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Foot', N'Foot maps to 27', N'27');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Hour', N'Hour maps to 28', N'28');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'12 Hour', N'12 Hour maps to 29', N'29');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'16 Hour', N'16 Hour maps to 30', N'30');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'24 Hour', N'24 Hour maps to 31', N'31');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'4 Hour', N'4 Hour maps to 32', N'32');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'40 Hour', N'40 Hour maps to 33', N'33');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'8 Hour', N'8 Hour maps to 34', N'34');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Day', N'Day maps to 35', N'35');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Minute', N'Minute maps to 36', N'36');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Month', N'Month maps to 37', N'37');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Week', N'Week maps to 38', N'38');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Year', N'Year maps to 39', N'39');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Centimeter', N'Cubic Centimeter maps to 40', N'40');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Inch', N'Cubic Inch maps to 42', N'42');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Meter', N'Cubic Meter maps to 43', N'43');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cubic Yard', N'Cubic Yard maps to 44', N'44');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Fluid Ounce', N'Fluid Ounce maps to 45', N'45');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Pint', N'Pint maps to 48', N'48');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Grain', N'Grain maps to 51', N'51');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Gram', N'Gram maps to 52', N'52');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Kilogram', N'Kilogram maps to 53', N'53');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Metric Pound', N'Metric Pound maps to 54', N'54');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Metric Ton', N'Metric Ton maps to 55', N'55');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Milligram', N'Milligram maps to 56', N'56');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Ton', N'Ton maps to 58', N'58');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Percent', N'Percent maps to 59', N'59');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Default Weight Unit', N'Default Weight Unit maps to 100', N'100');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Default Volume Unit', N'Default Volume Unit maps to 700', N'700');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'AltShip Unit', N'AltShip Unit maps to 800', N'800');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Margin', N'Margin maps to 5,000', N'5,000');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cost', N'Cost maps to 5,100', N'5,100');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Case', N'Case maps to 10,001', N'10,001');

In [50]:
original_copy= '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');'''
print(original_copy+"\n")
comilla = "'"
nombre = 'CARLOS'
numero = '2300'
query = '''INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'''
query2 = '''', N'''
query3 = ''' maps to '''
query4='''', N'''
query5= ''');'''

list_category = ('Area','Length','Time','Percentage','ALTSHIPUNIT','Margin','Cost','Cartons')
list_code = ('50','30','130','1,003','80','500','510','1,001')
k=0
j=0
print(len(list_category))
for j in range (len(list_category)):
    for k in range (k<=len(list_category)):
        print (query+comilla + list_category[j]+query2+comilla+list_category[j]+query3+list_code[j]+query4+comilla+ list_code[j]+comilla+query5)

INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'CURRENCY', N'CURRENCY maps to 110', N'110');

8
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Area', N'Area maps to 50', N'50');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Length', N'Length maps to 30', N'30');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Time', N'Time maps to 130', N'130');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Percentage', N'Percentage maps to 1,003', N'1,003');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'ALTSHIPUNIT', N'ALTSHIPUNIT maps to 80', N'80');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Margin', N'Margin maps to 500', N'500');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cost', N'Cost maps to 510', N'510');
INSERT [CRTD].[CRTD_COMMON_LOOKUP] ([LOOKUP], [FROM_VALUE], [DESCR], [TO_VALUE])
VALUES (N'LKUP_UOM_FROMUOM', N'Cartons', N'Cartons maps to 1,001', N'1,001');